-- RI6900 manual component ledger
-- Paste this entire file into Supabase SQL Editor and click Run.
-- It is idempotent: running it again does not delete recorded scans.

create extension if not exists pgcrypto;

create table if not exists public.scout_signals (
  id uuid primary key default gen_random_uuid(),
  chain text not null default 'solana',
  mint text not null unique,
  name text not null,
  symbol text not null,
  source text not null default 'manual',
  source_chat_id text,
  source_message_id text,
  source_url text,
  status text not null default 'passed'
    check (status in ('queued', 'active', 'passed', 'rejected', 'archived')),
  scout_score numeric check (scout_score is null or scout_score between 0 and 100),
  price_usd numeric,
  market_cap_usd numeric,
  liquidity_usd numeric,
  volume_24h_usd numeric,
  holder_count integer,
  token_age_seconds integer,
  metrics jsonb not null default '{}'::jsonb,
  reasons text[] not null default '{}',
  risk_flags text[] not null default '{}',
  selection_reason text,
  detected_at timestamptz not null default now(),
  selected_at timestamptz,
  public_at timestamptz not null default now(),
  retired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep this compatible with an older Runner table if it already exists.
alter table public.scout_signals add column if not exists source_url text;
alter table public.scout_signals add column if not exists source_chat_id text;
alter table public.scout_signals add column if not exists source_message_id text;
alter table public.scout_signals add column if not exists scout_score numeric;
alter table public.scout_signals add column if not exists price_usd numeric;
alter table public.scout_signals add column if not exists market_cap_usd numeric;
alter table public.scout_signals add column if not exists liquidity_usd numeric;
alter table public.scout_signals add column if not exists volume_24h_usd numeric;
alter table public.scout_signals add column if not exists holder_count integer;
alter table public.scout_signals add column if not exists token_age_seconds integer;
alter table public.scout_signals add column if not exists metrics jsonb not null default '{}'::jsonb;
alter table public.scout_signals add column if not exists reasons text[] not null default '{}';
alter table public.scout_signals add column if not exists risk_flags text[] not null default '{}';
alter table public.scout_signals add column if not exists selection_reason text;
alter table public.scout_signals add column if not exists detected_at timestamptz not null default now();
alter table public.scout_signals add column if not exists selected_at timestamptz;
alter table public.scout_signals add column if not exists public_at timestamptz not null default now();
alter table public.scout_signals add column if not exists retired_at timestamptz;
alter table public.scout_signals add column if not exists created_at timestamptz not null default now();
alter table public.scout_signals add column if not exists updated_at timestamptz not null default now();

create unique index if not exists scout_signals_mint_idx on public.scout_signals (mint);
create unique index if not exists scout_signals_one_active_idx
  on public.scout_signals ((status)) where status = 'active';
create index if not exists scout_signals_public_idx
  on public.scout_signals (public_at desc) where status in ('active', 'passed', 'archived');
create index if not exists scout_signals_detected_idx
  on public.scout_signals (detected_at desc);

create table if not exists public.scout_signal_events (
  id bigint generated by default as identity primary key,
  signal_id uuid references public.scout_signals(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists scout_signal_events_signal_idx
  on public.scout_signal_events (signal_id, created_at desc);

create table if not exists public.scout_settings (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

insert into public.scout_settings (key, value, description) values
  ('eligibility_minimum', '1000000', 'Minimum RI6900 balance for holder distributions.'),
  ('public_signal_delay_seconds', '0', 'Manual RI6900 components are published immediately.')
on conflict (key) do update
set value = excluded.value,
    description = excluded.description,
    updated_at = now();

alter table public.scout_signals enable row level security;
alter table public.scout_signal_events enable row level security;
alter table public.scout_settings enable row level security;

drop policy if exists "public reads released scout signals" on public.scout_signals;
create policy "public reads released scout signals"
  on public.scout_signals for select
  using (public_at <= now() and status in ('active', 'passed', 'archived'));

drop policy if exists "public reads released scout events" on public.scout_signal_events;
create policy "public reads released scout events"
  on public.scout_signal_events for select
  using (
    exists (
      select 1 from public.scout_signals signal
      where signal.id = signal_id
        and signal.public_at <= now()
        and signal.status in ('active', 'passed', 'archived')
    )
  );

drop policy if exists "public reads scout settings" on public.scout_settings;
create policy "public reads scout settings"
  on public.scout_settings for select
  using (key in ('eligibility_minimum', 'public_signal_delay_seconds'));

grant select on public.scout_signals, public.scout_signal_events, public.scout_settings to anon, authenticated;
grant all on public.scout_signals, public.scout_signal_events, public.scout_settings to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Setup complete. Use record_runner_scan.sql for each new active Runner.
