-- RUNNER manual scan ledger
-- Paste this entire file into Supabase SQL Editor and click Run.
-- It is idempotent: running it again does not delete recorded scans.

create extension if not exists pgcrypto;

create table if not exists public.scout_signals (
  id uuid primary key default gen_random_uuid(),
  chain text not null default 'solana',
  mint text not null unique,
  name text not null,
  symbol text not null,
  source text not null default 'manual',
  source_chat_id text,
  source_message_id text,
  source_url text,
  status text not null default 'passed'
    check (status in ('queued', 'active', 'passed', 'rejected', 'archived')),
  scout_score numeric check (scout_score is null or scout_score between 0 and 100),
  price_usd numeric,
  market_cap_usd numeric,
  liquidity_usd numeric,
  volume_24h_usd numeric,
  holder_count integer,
  token_age_seconds integer,
  metrics jsonb not null default '{}'::jsonb,
  reasons text[] not null default '{}',
  risk_flags text[] not null default '{}',
  selection_reason text,
  detected_at timestamptz not null default now(),
  selected_at timestamptz,
  public_at timestamptz not null default now(),
  retired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep this compatible with an older Runner table if it already exists.
alter table public.scout_signals add column if not exists source_url text;
alter table public.scout_signals add column if not exists source_chat_id text;
alter table public.scout_signals add column if not exists source_message_id text;
alter table public.scout_signals add column if not exists scout_score numeric;
alter table public.scout_signals add column if not exists price_usd numeric;
alter table public.scout_signals add column if not exists market_cap_usd numeric;
alter table public.scout_signals add column if not exists liquidity_usd numeric;
alter table public.scout_signals add column if not exists volume_24h_usd numeric;
alter table public.scout_signals add column if not exists holder_count integer;
alter table public.scout_signals add column if not exists token_age_seconds integer;
alter table public.scout_signals add column if not exists metrics jsonb not null default '{}'::jsonb;
alter table public.scout_signals add column if not exists reasons text[] not null default '{}';
alter table public.scout_signals add column if not exists risk_flags text[] not null default '{}';
alter table public.scout_signals add column if not exists selection_reason text;
alter table public.scout_signals add column if not exists detected_at timestamptz not null default now();
alter table public.scout_signals add column if not exists selected_at timestamptz;
alter table public.scout_signals add column if not exists public_at timestamptz not null default now();
alter table public.scout_signals add column if not exists retired_at timestamptz;
alter table public.scout_signals add column if not exists created_at timestamptz not null default now();
alter table public.scout_signals add column if not exists updated_at timestamptz not null default now();

create unique index if not exists scout_signals_mint_idx on public.scout_signals (mint);
create unique index if not exists scout_signals_one_active_idx
  on public.scout_signals ((status)) where status = 'active';
create index if not exists scout_signals_public_idx
  on public.scout_signals (public_at desc) where status in ('active', 'passed', 'archived');
create index if not exists scout_signals_detected_idx
  on public.scout_signals (detected_at desc);

create table if not exists public.scout_signal_events (
  id bigint generated by default as identity primary key,
  signal_id uuid references public.scout_signals(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists scout_signal_events_signal_idx
  on public.scout_signal_events (signal_id, created_at desc);

create table if not exists public.scout_settings (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

insert into public.scout_settings (key, value, description) values
  ('eligibility_minimum', '1000000', 'Minimum RUNNER balance for holder distributions.'),
  ('public_signal_delay_seconds', '0', 'Manual Runner scans are published immediately.')
on conflict (key) do update
set value = excluded.value,
    description = excluded.description,
    updated_at = now();

-- One safe command for recording a scan. Market cap is the snapshot at scan time.
-- The website obtains current market cap live from DexScreener by mint address.
create or replace function public.record_runner_scan(
  p_mint text,
  p_name text,
  p_symbol text,
  p_market_cap_usd numeric,
  p_detected_at timestamptz default now(),
  p_status text default 'active',
  p_scout_score numeric default null,
  p_selection_reason text default null
)
returns public.scout_signals
language plpgsql
security definer
set search_path = public
as $$
declare
  recorded public.scout_signals;
begin
  if p_mint is null or btrim(p_mint) = '' then
    raise exception 'Mint is required';
  end if;
  if p_name is null or btrim(p_name) = '' then
    raise exception 'Token name is required';
  end if;
  if p_symbol is null or btrim(p_symbol) = '' then
    raise exception 'Token symbol is required';
  end if;
  if p_market_cap_usd is null or p_market_cap_usd < 0 then
    raise exception 'Market cap at scan must be zero or greater';
  end if;
  if p_status not in ('active', 'passed', 'archived') then
    raise exception 'Manual scan status must be active, passed, or archived';
  end if;
  if p_scout_score is not null and (p_scout_score < 0 or p_scout_score > 100) then
    raise exception 'Scout score must be between 0 and 100';
  end if;

  if p_status = 'active' then
    update public.scout_signals
    set status = 'passed', retired_at = p_detected_at, updated_at = now()
    where status = 'active' and mint <> btrim(p_mint);
  end if;

  insert into public.scout_signals (
    chain, mint, name, symbol, source, source_url, status, scout_score,
    market_cap_usd, selection_reason, detected_at, selected_at, public_at,
    retired_at, updated_at
  ) values (
    'solana', btrim(p_mint), btrim(p_name), upper(btrim(p_symbol)), 'manual',
    'https://dexscreener.com/solana/' || btrim(p_mint), p_status, p_scout_score,
    p_market_cap_usd, p_selection_reason, p_detected_at,
    case when p_status = 'active' then p_detected_at else null end,
    p_detected_at, null, now()
  )
  on conflict (mint) do update set
    name = excluded.name,
    symbol = excluded.symbol,
    source = excluded.source,
    source_url = excluded.source_url,
    status = excluded.status,
    scout_score = excluded.scout_score,
    market_cap_usd = excluded.market_cap_usd,
    selection_reason = excluded.selection_reason,
    detected_at = excluded.detected_at,
    selected_at = excluded.selected_at,
    public_at = excluded.public_at,
    retired_at = excluded.retired_at,
    updated_at = now()
  returning * into recorded;

  insert into public.scout_signal_events (signal_id, event_type, payload)
  values (
    recorded.id,
    case when p_status = 'active' then 'target_locked' else 'scan_recorded' end,
    jsonb_build_object('market_cap_at_scan_usd', p_market_cap_usd, 'source', 'manual')
  );

  return recorded;
end;
$$;

alter table public.scout_signals enable row level security;
alter table public.scout_signal_events enable row level security;
alter table public.scout_settings enable row level security;

drop policy if exists "public reads released scout signals" on public.scout_signals;
create policy "public reads released scout signals"
  on public.scout_signals for select
  using (public_at <= now() and status in ('active', 'passed', 'archived'));

drop policy if exists "public reads released scout events" on public.scout_signal_events;
create policy "public reads released scout events"
  on public.scout_signal_events for select
  using (
    exists (
      select 1 from public.scout_signals signal
      where signal.id = signal_id
        and signal.public_at <= now()
        and signal.status in ('active', 'passed', 'archived')
    )
  );

drop policy if exists "public reads scout settings" on public.scout_settings;
create policy "public reads scout settings"
  on public.scout_settings for select
  using (key in ('eligibility_minimum', 'public_signal_delay_seconds'));

grant select on public.scout_signals, public.scout_signal_events, public.scout_settings to anon, authenticated;
grant all on public.scout_signals, public.scout_signal_events, public.scout_settings to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function public.record_runner_scan(text, text, text, numeric, timestamptz, text, numeric, text) from public, anon, authenticated;
grant execute on function public.record_runner_scan(text, text, text, numeric, timestamptz, text, numeric, text) to service_role;

-- EXAMPLE: replace the values, then run only this SELECT for each new scan.
-- Use 'active' for the current Runner or 'passed' for a historical call.
-- select public.record_runner_scan(
--   'SOLANA_MINT_ADDRESS',
--   'Token Name',
--   'SYMBOL',
--   125000,
--   '2026-07-21 14:04:00-04',
--   'active',
--   null,
--   'Manual verified Runner scan'
-- );
