create extension if not exists pgcrypto;

create table if not exists public.scout_signals (
  id uuid primary key default gen_random_uuid(),
  chain text not null default 'solana',
  mint text not null unique,
  name text not null,
  symbol text not null,
  source text not null default 'admin',
  source_chat_id text,
  source_message_id text,
  source_url text,
  status text not null default 'queued'
    check (status in ('queued', 'active', 'passed', 'rejected', 'archived')),
  scout_score numeric check (scout_score is null or scout_score between 0 and 100),
  price_usd numeric,
  market_cap_usd numeric,
  liquidity_usd numeric,
  volume_24h_usd numeric,
  holder_count integer,
  token_age_seconds integer,
  metrics jsonb not null default '{}'::jsonb,
  reasons text[] not null default '{}',
  risk_flags text[] not null default '{}',
  selection_reason text,
  detected_at timestamptz not null default now(),
  selected_at timestamptz,
  public_at timestamptz not null default (now() + interval '1 minute'),
  retired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists scout_signals_one_active_idx
  on public.scout_signals ((status)) where status = 'active';
create index if not exists scout_signals_public_idx
  on public.scout_signals (public_at desc) where status in ('active', 'passed', 'archived');
create index if not exists scout_signals_score_idx
  on public.scout_signals (scout_score desc nulls last, detected_at desc);

create table if not exists public.scout_signal_events (
  id bigint generated by default as identity primary key,
  signal_id uuid references public.scout_signals(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists scout_signal_events_signal_idx
  on public.scout_signal_events (signal_id, created_at desc);

create table if not exists public.scout_settings (
  key text primary key,
  value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

insert into public.scout_settings (key, value, description) values
  ('eligibility_minimum', '1000000', 'Minimum RUNNER balance for holder distributions.'),
  ('public_signal_delay_seconds', '60', 'Delay before a premium signal becomes public.'),
  ('distribution_bps', '6000', 'Target share of protocol revenue reserved for holder distributions.'),
  ('protocol_reserve_bps', '4000', 'Target share reserved for buybacks, burns, operations, and growth.'),
  ('minimum_scout_score', '60', 'Minimum score accepted by automated signal ingestion.'),
  ('minimum_liquidity_usd', '5000', 'Minimum reported liquidity accepted by automated ingestion.'),
  ('minimum_active_seconds', '300', 'Minimum time an active signal remains selected unless an administrator overrides it.'),
  ('switch_score_margin', '8', 'Required score advantage before an automated signal replaces the active selection.')
on conflict (key) do nothing;

create table if not exists public.scout_delivery_queue (
  id bigint generated by default as identity primary key,
  signal_id uuid not null references public.scout_signals(id) on delete cascade,
  destination text not null check (destination in ('premium', 'public')),
  chat_id text not null,
  due_at timestamptz not null,
  status text not null default 'queued'
    check (status in ('queued', 'sending', 'sent', 'failed', 'cancelled')),
  attempts integer not null default 0,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (signal_id, destination, chat_id)
);

create index if not exists scout_delivery_queue_due_idx
  on public.scout_delivery_queue (status, due_at);

create table if not exists public.scout_group_configs (
  chat_id text primary key,
  title text,
  plan text not null default 'starter' check (plan in ('starter', 'pro', 'enterprise')),
  minimum_score numeric not null default 70 check (minimum_score between 0 and 100),
  maximum_market_cap_usd numeric,
  chains text[] not null default array['solana'],
  frequency_seconds integer not null default 300,
  alert_types text[] not null default array['selected'],
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scout_watchlists (
  wallet text not null,
  mint text not null,
  created_at timestamptz not null default now(),
  primary key (wallet, mint)
);

create table if not exists public.scout_api_keys (
  id uuid primary key default gen_random_uuid(),
  owner_label text not null,
  key_prefix text not null,
  key_hash text not null unique,
  tier text not null default 'starter' check (tier in ('starter', 'pro', 'enterprise')),
  rate_limit_per_minute integer not null default 30,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create table if not exists public.scout_access_challenges (
  id uuid primary key default gen_random_uuid(),
  wallet text not null,
  nonce text not null unique,
  message text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists scout_access_challenges_wallet_idx
  on public.scout_access_challenges (wallet, created_at desc);

create table if not exists public.scout_access_sessions (
  id uuid primary key default gen_random_uuid(),
  wallet text not null,
  token_hash text not null unique,
  source_balance numeric not null default 0,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists scout_access_sessions_wallet_idx
  on public.scout_access_sessions (wallet, expires_at desc);

do $$
begin
  if to_regclass('public.epochs') is not null then
    alter table public.epochs add column if not exists scout_signal_id uuid references public.scout_signals(id);
  end if;
end $$;

create or replace function public.scout_activate_signal(target_signal_id uuid, reason text default null)
returns public.scout_signals
language plpgsql
security definer
set search_path = public
as $$
declare
  activated public.scout_signals;
begin
  update public.scout_signals
  set status = 'passed', retired_at = now(), updated_at = now()
  where status = 'active' and id <> target_signal_id;

  update public.scout_signals
  set status = 'active', selected_at = coalesce(selected_at, now()), retired_at = null,
      selection_reason = coalesce(reason, selection_reason), updated_at = now()
  where id = target_signal_id
  returning * into activated;

  if activated.id is null then
    raise exception 'Scout signal % not found', target_signal_id;
  end if;

  insert into public.scout_signal_events (signal_id, event_type, payload)
  values (target_signal_id, 'activated', jsonb_build_object('reason', reason));

  return activated;
end;
$$;

alter table public.scout_signals enable row level security;
alter table public.scout_signal_events enable row level security;
alter table public.scout_settings enable row level security;
alter table public.scout_delivery_queue enable row level security;
alter table public.scout_group_configs enable row level security;
alter table public.scout_watchlists enable row level security;
alter table public.scout_api_keys enable row level security;
alter table public.scout_access_challenges enable row level security;
alter table public.scout_access_sessions enable row level security;

drop policy if exists "public reads released scout signals" on public.scout_signals;
create policy "public reads released scout signals"
  on public.scout_signals for select
  using (public_at <= now() and status in ('active', 'passed', 'archived'));

drop policy if exists "public reads released scout events" on public.scout_signal_events;
create policy "public reads released scout events"
  on public.scout_signal_events for select
  using (
    exists (
      select 1 from public.scout_signals signal
      where signal.id = signal_id
        and signal.public_at <= now()
        and signal.status in ('active', 'passed', 'archived')
    )
  );

drop policy if exists "public reads scout settings" on public.scout_settings;
create policy "public reads scout settings"
  on public.scout_settings for select
  using (key in ('eligibility_minimum', 'public_signal_delay_seconds', 'distribution_bps', 'protocol_reserve_bps'));

grant select on public.scout_signals, public.scout_signal_events, public.scout_settings to anon, authenticated;
grant all on public.scout_signals, public.scout_signal_events, public.scout_settings,
  public.scout_delivery_queue, public.scout_group_configs, public.scout_watchlists, public.scout_api_keys,
  public.scout_access_challenges, public.scout_access_sessions to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.scout_activate_signal(uuid, text) to service_role;
