create table if not exists public.casino_rounds (
  round_id text primary key,
  round_sequence bigint generated by default as identity unique,
  epoch_id text not null unique references public.epochs(epoch_id) on delete cascade,
  game text not null,
  status text not null default 'awaiting_randomness'
    check (status in ('awaiting_randomness', 'ready', 'settling', 'settled', 'skipped', 'failed')),
  eligible_count integer not null default 0 check (eligible_count >= 0),
  snapshot_hash text not null,
  claimed_lamports numeric(40, 0) not null default 0 check (claimed_lamports >= 0),
  round_pool_lamports numeric(40, 0) not null default 0 check (round_pool_lamports >= 0),
  jackpot_opening_lamports numeric(40, 0) not null default 0 check (jackpot_opening_lamports >= 0),
  jackpot_contribution_lamports numeric(40, 0) not null default 0 check (jackpot_contribution_lamports >= 0),
  jackpot_payout_lamports numeric(40, 0) not null default 0 check (jackpot_payout_lamports >= 0),
  jackpot_closing_lamports numeric(40, 0) not null default 0 check (jackpot_closing_lamports >= 0),
  is_jackpot_round boolean not null default false,
  randomness_provider text,
  randomness_account text,
  randomness_commit_slot bigint,
  randomness_hex text,
  randomness_commit_tx_sig text,
  randomness_reveal_tx_sig text,
  randomness_verified_at timestamptz,
  settlement_tx_sig text,
  settlement_transaction_base64 text,
  settlement_last_valid_block_height bigint,
  started_at timestamptz not null default now(),
  settled_at timestamptz,
  error text,
  constraint casino_rounds_randomness_hex_check
    check (randomness_hex is null or randomness_hex ~ '^[0-9a-fA-F]{64}$'),
  constraint casino_rounds_verified_randomness_check
    check (
      randomness_verified_at is null
      or (
        randomness_provider = 'switchboard'
        and randomness_account is not null
        and randomness_commit_slot is not null
        and randomness_hex is not null
        and randomness_commit_tx_sig is not null
        and randomness_reveal_tx_sig is not null
      )
    )
);

create table if not exists public.casino_winners (
  round_id text not null references public.casino_rounds(round_id) on delete cascade,
  position smallint not null check (position between 1 and 3),
  wallet text not null,
  selection_score text not null,
  round_payout_lamports numeric(40, 0) not null default 0 check (round_payout_lamports >= 0),
  jackpot_payout_lamports numeric(40, 0) not null default 0 check (jackpot_payout_lamports >= 0),
  total_payout_lamports numeric(40, 0) not null default 0 check (total_payout_lamports >= 0),
  status text not null check (status in ('planned', 'settled', 'failed', 'dry_run')),
  tx_sig text,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (round_id, position),
  unique (round_id, wallet)
);

create index if not exists casino_rounds_status_sequence_idx
  on public.casino_rounds(status, round_sequence);
create index if not exists casino_rounds_settled_at_idx
  on public.casino_rounds(settled_at desc);
create unique index if not exists casino_rounds_randomness_commitment_uidx
  on public.casino_rounds(randomness_account, randomness_commit_slot)
  where randomness_account is not null and randomness_commit_slot is not null;
create index if not exists casino_winners_round_status_idx
  on public.casino_winners(round_id, status);
create index if not exists casino_winners_wallet_idx
  on public.casino_winners(wallet);

create or replace function public.guard_casino_round_commitment()
returns trigger
language plpgsql
as $$
begin
  if old.snapshot_hash is distinct from new.snapshot_hash then
    raise exception 'casino snapshot commitment is immutable';
  end if;

  if old.randomness_commit_tx_sig is not null and (
    old.randomness_provider is distinct from new.randomness_provider
    or old.randomness_account is distinct from new.randomness_account
    or old.randomness_commit_slot is distinct from new.randomness_commit_slot
    or old.randomness_commit_tx_sig is distinct from new.randomness_commit_tx_sig
  ) then
    raise exception 'casino randomness commitment is immutable';
  end if;

  if old.randomness_verified_at is not null and (
    old.randomness_hex is distinct from new.randomness_hex
    or old.randomness_reveal_tx_sig is distinct from new.randomness_reveal_tx_sig
    or old.randomness_verified_at is distinct from new.randomness_verified_at
  ) then
    raise exception 'verified casino randomness is immutable';
  end if;

  if old.status = 'settled' and old is distinct from new then
    raise exception 'settled casino rounds are immutable';
  end if;

  return new;
end;
$$;

drop trigger if exists casino_round_commitment_guard on public.casino_rounds;
create trigger casino_round_commitment_guard
before update on public.casino_rounds
for each row execute function public.guard_casino_round_commitment();

alter table public.casino_rounds enable row level security;
alter table public.casino_winners enable row level security;

drop policy if exists "public read settled casino rounds" on public.casino_rounds;
drop policy if exists "public read settled casino winners" on public.casino_winners;

create policy "public read settled casino rounds" on public.casino_rounds
  for select using (status = 'settled');

create policy "public read settled casino winners" on public.casino_winners
  for select using (status = 'settled');
