alter table public.casino_rounds
  add column if not exists playback_started_at timestamptz,
  add column if not exists playback_ends_at timestamptz,
  add column if not exists results_committed_at timestamptz,
  add column if not exists results_hash text;

alter table public.casino_rounds
  drop constraint if exists casino_rounds_results_hash_check;

alter table public.casino_rounds
  add constraint casino_rounds_results_hash_check
    check (results_hash is null or results_hash ~ '^[0-9a-f]{64}$');

create table if not exists public.casino_game_results (
  round_id text not null references public.casino_rounds(round_id) on delete cascade,
  wallet text not null,
  sequence_index integer not null check (sequence_index > 0),
  game text not null,
  score numeric(78, 0) not null check (score >= 0),
  tie_break text not null check (tie_break ~ '^[0-9a-f]{64}$'),
  summary text not null check (char_length(summary) between 1 and 160),
  outcome jsonb not null default '{}'::jsonb,
  result_hash text not null check (result_hash ~ '^[0-9a-f]{64}$'),
  scheduled_at timestamptz not null,
  created_at timestamptz not null default now(),
  primary key (round_id, wallet),
  unique (round_id, sequence_index)
);

create index if not exists casino_game_results_round_schedule_idx
  on public.casino_game_results(round_id, scheduled_at, sequence_index);

create index if not exists casino_game_results_round_score_idx
  on public.casino_game_results(round_id, score desc, tie_break);

create table if not exists public.casino_chat_messages (
  id bigint generated by default as identity primary key,
  author text not null check (author ~ '^[A-Za-z0-9_-]{2,24}$'),
  body text not null check (char_length(body) between 1 and 240),
  author_hash text not null check (author_hash ~ '^[0-9a-f]{64}$'),
  moderation_status text not null default 'approved'
    check (moderation_status in ('approved', 'hidden')),
  created_at timestamptz not null default now()
);

create index if not exists casino_chat_messages_created_idx
  on public.casino_chat_messages(created_at desc);

create index if not exists casino_chat_messages_author_rate_idx
  on public.casino_chat_messages(author_hash, created_at desc);

create or replace function public.guard_casino_game_result()
returns trigger
language plpgsql
as $$
begin
  if old is distinct from new then
    raise exception 'casino game results are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists casino_game_result_guard on public.casino_game_results;
create trigger casino_game_result_guard
before update on public.casino_game_results
for each row execute function public.guard_casino_game_result();

create or replace function public.guard_casino_round_results()
returns trigger
language plpgsql
as $$
begin
  if old.results_hash is not null and (
    old.results_hash is distinct from new.results_hash
    or old.results_committed_at is distinct from new.results_committed_at
    or old.playback_started_at is distinct from new.playback_started_at
    or old.playback_ends_at is distinct from new.playback_ends_at
  ) then
    raise exception 'committed casino game results are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists casino_round_results_guard on public.casino_rounds;
create trigger casino_round_results_guard
before update on public.casino_rounds
for each row execute function public.guard_casino_round_results();

alter table public.casino_game_results enable row level security;
alter table public.casino_chat_messages enable row level security;

drop policy if exists "public read committed casino playback rounds" on public.casino_rounds;
drop policy if exists "public read revealed casino game results" on public.casino_game_results;
drop policy if exists "public read approved casino chat" on public.casino_chat_messages;

create policy "public read committed casino playback rounds" on public.casino_rounds
  for select using (results_hash is not null and randomness_verified_at is not null);

create policy "public read revealed casino game results" on public.casino_game_results
  for select using (scheduled_at <= now());

create policy "public read approved casino chat" on public.casino_chat_messages
  for select using (moderation_status = 'approved');

-- The public live feed needs active-round metadata, but it must never expose the
-- revealed random bytes that would let a client calculate unrevealed playback.
create or replace view public.casino_public_rounds as
select
  round_id,
  round_sequence,
  game,
  status,
  eligible_count,
  started_at,
  playback_started_at,
  playback_ends_at,
  results_hash,
  randomness_provider,
  randomness_account,
  randomness_commit_tx_sig,
  randomness_reveal_tx_sig,
  randomness_verified_at,
  settlement_tx_sig,
  settled_at
from public.casino_rounds;

-- Reveal exactly one in-progress play. Later outcomes remain inaccessible until
-- their own playback window begins.
create or replace view public.casino_public_current_play as
select
  result.round_id,
  result.wallet,
  result.sequence_index,
  result.game,
  result.score,
  result.tie_break,
  result.summary,
  result.outcome,
  result.result_hash,
  result.scheduled_at
from public.casino_game_results result
where result.sequence_index = (
  select min(candidate.sequence_index)
  from public.casino_game_results candidate
  where candidate.round_id = result.round_id
    and candidate.scheduled_at > now()
);

revoke all on public.casino_public_rounds from public;
revoke all on public.casino_public_current_play from public;
grant select on public.casino_public_rounds to anon, authenticated, service_role;
grant select on public.casino_public_current_play to anon, authenticated, service_role;
